package com.tmsps.ne4SpringBoot.bean;

import com.tmsps.ne4spring.annotation.NotMap;
import com.tmsps.ne4spring.annotation.PK;
import com.tmsps.ne4spring.annotation.Table;
import com.tmsps.ne4spring.orm.model.DataModel;

/**
 * Generated by ne4SpringBoot 
*/

@Table(TableName="test")
public class test extends DataModel {

	@NotMap
	private static final long serialVersionUID = 1L;
	@PK
	private java.lang.String id;
	public void setId(java.lang.String id) {
 		this.id = id;
	}

	public java.lang.String getId() {
		return id;
	}

}